
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=ibisripley
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=widgetdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_table.sql
    shm_size: 256mb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
